### PR TITLE
Travis setup

### PR DESCRIPTION
**Pull request by TimNN**
This is ready to be merged as soon as the deploy key has been added to GitHub.

Automatic deployment to GitHub pages using ([hugo](https://gohugo.io/)) has been setup now and should be mostly working.

Open questions:
- http://hpi-swa-teaching.github.io/SWT16-Project-14/ is a really annoying url, I would like to set up a CNAME to something simpler, I could provide http://etoys-notes.timnn.me/ but am open for alternatives.

### CODE REVIEW

**Comment by TimNN** [comment]
I have prepared automatic publishing to GitHub pages using a deploy key.

Once this PR has been reviewed, the following public key needs to be added to this repository:

```
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFeN+Kc2wiJHB31J1Aa0/ujPkRgyPYb8+z3aJ+uqKU+ThNENM4W2skdnjiEMMzPPGUf3HQzdkuYvRizn1YA6K+k= travis@swt
```

**Edit:** `ssh-add` was asking for a passphrase with the `ssh-ed25519` key, so I switched to a `ecdsa-sha2-nistp256` key.

**Comment by TimNN** [comment]
@fniephaus: Could you please add

```
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFeN+Kc2wiJHB31J1Aa0/ujPkRgyPYb8+z3aJ+uqKU+ThNENM4W2skdnjiEMMzPPGUf3HQzdkuYvRizn1YA6K+k= travis@swt
```

as a deploy key to this repository with read & write access?

**Comment by fniephaus** [comment]
Done!

**Comment by TimNN** [comment]
@fniephaus: Thanks!

**Pull request merged**
